spring:
  datasource:
    username: admin
    password: admin123
    url: jdbc:mysql://raj-db.cvaqouqia3d4.us-east-1.rds.amazonaws.com:3306/sbidb
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
